# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_gen import cosmos_pb2 as cosmos__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cosmos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraphRAGServiceStub(object):
    """============================================================
    GraphRAG Service
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestModuleDeps = channel.unary_unary(
                '/cosmos.GraphRAGService/IngestModuleDeps',
                request_serializer=cosmos__pb2.IngestModuleDepsRequest.SerializeToString,
                response_deserializer=cosmos__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.IngestCourierRelationship = channel.unary_unary(
                '/cosmos.GraphRAGService/IngestCourierRelationship',
                request_serializer=cosmos__pb2.IngestCourierRequest.SerializeToString,
                response_deserializer=cosmos__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.IngestChannelRelationship = channel.unary_unary(
                '/cosmos.GraphRAGService/IngestChannelRelationship',
                request_serializer=cosmos__pb2.IngestChannelRequest.SerializeToString,
                response_deserializer=cosmos__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.QueryRelated = channel.unary_unary(
                '/cosmos.GraphRAGService/QueryRelated',
                request_serializer=cosmos__pb2.GraphQueryRequest.SerializeToString,
                response_deserializer=cosmos__pb2.GraphQueryResponse.FromString,
                _registered_method=True)
        self.Traverse = channel.unary_unary(
                '/cosmos.GraphRAGService/Traverse',
                request_serializer=cosmos__pb2.TraverseRequest.SerializeToString,
                response_deserializer=cosmos__pb2.TraversalResponse.FromString,
                _registered_method=True)
        self.GetShortestPath = channel.unary_unary(
                '/cosmos.GraphRAGService/GetShortestPath',
                request_serializer=cosmos__pb2.PathRequest.SerializeToString,
                response_deserializer=cosmos__pb2.TraversalResponse.FromString,
                _registered_method=True)
        self.FindNodes = channel.unary_unary(
                '/cosmos.GraphRAGService/FindNodes',
                request_serializer=cosmos__pb2.FindNodesRequest.SerializeToString,
                response_deserializer=cosmos__pb2.FindNodesResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/cosmos.GraphRAGService/GetStats',
                request_serializer=cosmos__pb2.StatsRequest.SerializeToString,
                response_deserializer=cosmos__pb2.GraphStatsResponse.FromString,
                _registered_method=True)
        self.TraverseStream = channel.unary_stream(
                '/cosmos.GraphRAGService/TraverseStream',
                request_serializer=cosmos__pb2.TraverseRequest.SerializeToString,
                response_deserializer=cosmos__pb2.TraversalNode.FromString,
                _registered_method=True)


class GraphRAGServiceServicer(object):
    """============================================================
    GraphRAG Service
    ============================================================

    """

    def IngestModuleDeps(self, request, context):
        """Ingest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestCourierRelationship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestChannelRelationship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryRelated(self, request, context):
        """Query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Traverse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShortestPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraverseStream(self, request, context):
        """Streaming: traverse large graphs incrementally
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphRAGServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestModuleDeps': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestModuleDeps,
                    request_deserializer=cosmos__pb2.IngestModuleDepsRequest.FromString,
                    response_serializer=cosmos__pb2.IngestResponse.SerializeToString,
            ),
            'IngestCourierRelationship': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestCourierRelationship,
                    request_deserializer=cosmos__pb2.IngestCourierRequest.FromString,
                    response_serializer=cosmos__pb2.IngestResponse.SerializeToString,
            ),
            'IngestChannelRelationship': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestChannelRelationship,
                    request_deserializer=cosmos__pb2.IngestChannelRequest.FromString,
                    response_serializer=cosmos__pb2.IngestResponse.SerializeToString,
            ),
            'QueryRelated': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryRelated,
                    request_deserializer=cosmos__pb2.GraphQueryRequest.FromString,
                    response_serializer=cosmos__pb2.GraphQueryResponse.SerializeToString,
            ),
            'Traverse': grpc.unary_unary_rpc_method_handler(
                    servicer.Traverse,
                    request_deserializer=cosmos__pb2.TraverseRequest.FromString,
                    response_serializer=cosmos__pb2.TraversalResponse.SerializeToString,
            ),
            'GetShortestPath': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShortestPath,
                    request_deserializer=cosmos__pb2.PathRequest.FromString,
                    response_serializer=cosmos__pb2.TraversalResponse.SerializeToString,
            ),
            'FindNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.FindNodes,
                    request_deserializer=cosmos__pb2.FindNodesRequest.FromString,
                    response_serializer=cosmos__pb2.FindNodesResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=cosmos__pb2.StatsRequest.FromString,
                    response_serializer=cosmos__pb2.GraphStatsResponse.SerializeToString,
            ),
            'TraverseStream': grpc.unary_stream_rpc_method_handler(
                    servicer.TraverseStream,
                    request_deserializer=cosmos__pb2.TraverseRequest.FromString,
                    response_serializer=cosmos__pb2.TraversalNode.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cosmos.GraphRAGService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cosmos.GraphRAGService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphRAGService(object):
    """============================================================
    GraphRAG Service
    ============================================================

    """

    @staticmethod
    def IngestModuleDeps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.GraphRAGService/IngestModuleDeps',
            cosmos__pb2.IngestModuleDepsRequest.SerializeToString,
            cosmos__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestCourierRelationship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.GraphRAGService/IngestCourierRelationship',
            cosmos__pb2.IngestCourierRequest.SerializeToString,
            cosmos__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestChannelRelationship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.GraphRAGService/IngestChannelRelationship',
            cosmos__pb2.IngestChannelRequest.SerializeToString,
            cosmos__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryRelated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.GraphRAGService/QueryRelated',
            cosmos__pb2.GraphQueryRequest.SerializeToString,
            cosmos__pb2.GraphQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Traverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.GraphRAGService/Traverse',
            cosmos__pb2.TraverseRequest.SerializeToString,
            cosmos__pb2.TraversalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShortestPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.GraphRAGService/GetShortestPath',
            cosmos__pb2.PathRequest.SerializeToString,
            cosmos__pb2.TraversalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.GraphRAGService/FindNodes',
            cosmos__pb2.FindNodesRequest.SerializeToString,
            cosmos__pb2.FindNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.GraphRAGService/GetStats',
            cosmos__pb2.StatsRequest.SerializeToString,
            cosmos__pb2.GraphStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TraverseStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cosmos.GraphRAGService/TraverseStream',
            cosmos__pb2.TraverseRequest.SerializeToString,
            cosmos__pb2.TraversalNode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VectorStoreServiceStub(object):
    """============================================================
    VectorStore Service
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmbedAndStore = channel.unary_unary(
                '/cosmos.VectorStoreService/EmbedAndStore',
                request_serializer=cosmos__pb2.EmbedRequest.SerializeToString,
                response_deserializer=cosmos__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.SearchSimilar = channel.unary_unary(
                '/cosmos.VectorStoreService/SearchSimilar',
                request_serializer=cosmos__pb2.SearchRequest.SerializeToString,
                response_deserializer=cosmos__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.BatchEmbed = channel.unary_unary(
                '/cosmos.VectorStoreService/BatchEmbed',
                request_serializer=cosmos__pb2.BatchEmbedRequest.SerializeToString,
                response_deserializer=cosmos__pb2.BatchEmbedResponse.FromString,
                _registered_method=True)
        self.DeleteByEntity = channel.unary_unary(
                '/cosmos.VectorStoreService/DeleteByEntity',
                request_serializer=cosmos__pb2.DeleteEmbeddingRequest.SerializeToString,
                response_deserializer=cosmos__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/cosmos.VectorStoreService/GetStats',
                request_serializer=cosmos__pb2.VectorStatsRequest.SerializeToString,
                response_deserializer=cosmos__pb2.VectorStatsResponse.FromString,
                _registered_method=True)
        self.SearchStream = channel.unary_stream(
                '/cosmos.VectorStoreService/SearchStream',
                request_serializer=cosmos__pb2.SearchRequest.SerializeToString,
                response_deserializer=cosmos__pb2.SearchResult.FromString,
                _registered_method=True)


class VectorStoreServiceServicer(object):
    """============================================================
    VectorStore Service
    ============================================================

    """

    def EmbedAndStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSimilar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchEmbed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteByEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchStream(self, request, context):
        """Stream search results as they're found
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmbedAndStore': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedAndStore,
                    request_deserializer=cosmos__pb2.EmbedRequest.FromString,
                    response_serializer=cosmos__pb2.EmbedResponse.SerializeToString,
            ),
            'SearchSimilar': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSimilar,
                    request_deserializer=cosmos__pb2.SearchRequest.FromString,
                    response_serializer=cosmos__pb2.SearchResponse.SerializeToString,
            ),
            'BatchEmbed': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchEmbed,
                    request_deserializer=cosmos__pb2.BatchEmbedRequest.FromString,
                    response_serializer=cosmos__pb2.BatchEmbedResponse.SerializeToString,
            ),
            'DeleteByEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteByEntity,
                    request_deserializer=cosmos__pb2.DeleteEmbeddingRequest.FromString,
                    response_serializer=cosmos__pb2.DeleteResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=cosmos__pb2.VectorStatsRequest.FromString,
                    response_serializer=cosmos__pb2.VectorStatsResponse.SerializeToString,
            ),
            'SearchStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchStream,
                    request_deserializer=cosmos__pb2.SearchRequest.FromString,
                    response_serializer=cosmos__pb2.SearchResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cosmos.VectorStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cosmos.VectorStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorStoreService(object):
    """============================================================
    VectorStore Service
    ============================================================

    """

    @staticmethod
    def EmbedAndStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.VectorStoreService/EmbedAndStore',
            cosmos__pb2.EmbedRequest.SerializeToString,
            cosmos__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSimilar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.VectorStoreService/SearchSimilar',
            cosmos__pb2.SearchRequest.SerializeToString,
            cosmos__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchEmbed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.VectorStoreService/BatchEmbed',
            cosmos__pb2.BatchEmbedRequest.SerializeToString,
            cosmos__pb2.BatchEmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteByEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.VectorStoreService/DeleteByEntity',
            cosmos__pb2.DeleteEmbeddingRequest.SerializeToString,
            cosmos__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.VectorStoreService/GetStats',
            cosmos__pb2.VectorStatsRequest.SerializeToString,
            cosmos__pb2.VectorStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cosmos.VectorStoreService/SearchStream',
            cosmos__pb2.SearchRequest.SerializeToString,
            cosmos__pb2.SearchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReportAgentServiceStub(object):
    """============================================================
    ReportAgent Service
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateWeeklyReport = channel.unary_unary(
                '/cosmos.ReportAgentService/GenerateWeeklyReport',
                request_serializer=cosmos__pb2.ReportRequest.SerializeToString,
                response_deserializer=cosmos__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.GenerateMonthlyReport = channel.unary_unary(
                '/cosmos.ReportAgentService/GenerateMonthlyReport',
                request_serializer=cosmos__pb2.ReportRequest.SerializeToString,
                response_deserializer=cosmos__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.GetReport = channel.unary_unary(
                '/cosmos.ReportAgentService/GetReport',
                request_serializer=cosmos__pb2.GetReportRequest.SerializeToString,
                response_deserializer=cosmos__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.ListReports = channel.unary_unary(
                '/cosmos.ReportAgentService/ListReports',
                request_serializer=cosmos__pb2.ListReportsRequest.SerializeToString,
                response_deserializer=cosmos__pb2.ListReportsResponse.FromString,
                _registered_method=True)
        self.GetReportMarkdown = channel.unary_unary(
                '/cosmos.ReportAgentService/GetReportMarkdown',
                request_serializer=cosmos__pb2.GetReportRequest.SerializeToString,
                response_deserializer=cosmos__pb2.MarkdownResponse.FromString,
                _registered_method=True)
        self.GenerateReportStream = channel.unary_stream(
                '/cosmos.ReportAgentService/GenerateReportStream',
                request_serializer=cosmos__pb2.ReportRequest.SerializeToString,
                response_deserializer=cosmos__pb2.ReportProgress.FromString,
                _registered_method=True)


class ReportAgentServiceServicer(object):
    """============================================================
    ReportAgent Service
    ============================================================

    """

    def GenerateWeeklyReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateMonthlyReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReportMarkdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReportStream(self, request, context):
        """Stream report generation progress
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateWeeklyReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateWeeklyReport,
                    request_deserializer=cosmos__pb2.ReportRequest.FromString,
                    response_serializer=cosmos__pb2.ReportResponse.SerializeToString,
            ),
            'GenerateMonthlyReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateMonthlyReport,
                    request_deserializer=cosmos__pb2.ReportRequest.FromString,
                    response_serializer=cosmos__pb2.ReportResponse.SerializeToString,
            ),
            'GetReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReport,
                    request_deserializer=cosmos__pb2.GetReportRequest.FromString,
                    response_serializer=cosmos__pb2.ReportResponse.SerializeToString,
            ),
            'ListReports': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReports,
                    request_deserializer=cosmos__pb2.ListReportsRequest.FromString,
                    response_serializer=cosmos__pb2.ListReportsResponse.SerializeToString,
            ),
            'GetReportMarkdown': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReportMarkdown,
                    request_deserializer=cosmos__pb2.GetReportRequest.FromString,
                    response_serializer=cosmos__pb2.MarkdownResponse.SerializeToString,
            ),
            'GenerateReportStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateReportStream,
                    request_deserializer=cosmos__pb2.ReportRequest.FromString,
                    response_serializer=cosmos__pb2.ReportProgress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cosmos.ReportAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cosmos.ReportAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReportAgentService(object):
    """============================================================
    ReportAgent Service
    ============================================================

    """

    @staticmethod
    def GenerateWeeklyReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.ReportAgentService/GenerateWeeklyReport',
            cosmos__pb2.ReportRequest.SerializeToString,
            cosmos__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateMonthlyReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.ReportAgentService/GenerateMonthlyReport',
            cosmos__pb2.ReportRequest.SerializeToString,
            cosmos__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.ReportAgentService/GetReport',
            cosmos__pb2.GetReportRequest.SerializeToString,
            cosmos__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.ReportAgentService/ListReports',
            cosmos__pb2.ListReportsRequest.SerializeToString,
            cosmos__pb2.ListReportsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReportMarkdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.ReportAgentService/GetReportMarkdown',
            cosmos__pb2.GetReportRequest.SerializeToString,
            cosmos__pb2.MarkdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReportStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cosmos.ReportAgentService/GenerateReportStream',
            cosmos__pb2.ReportRequest.SerializeToString,
            cosmos__pb2.ReportProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SandboxServiceStub(object):
    """============================================================
    Sandbox Service (Evaluation)
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSuite = channel.unary_unary(
                '/cosmos.SandboxService/CreateSuite',
                request_serializer=cosmos__pb2.CreateSuiteRequest.SerializeToString,
                response_deserializer=cosmos__pb2.SuiteResponse.FromString,
                _registered_method=True)
        self.ListSuites = channel.unary_unary(
                '/cosmos.SandboxService/ListSuites',
                request_serializer=cosmos__pb2.ListSuitesRequest.SerializeToString,
                response_deserializer=cosmos__pb2.ListSuitesResponse.FromString,
                _registered_method=True)
        self.AddTestCase = channel.unary_unary(
                '/cosmos.SandboxService/AddTestCase',
                request_serializer=cosmos__pb2.AddTestCaseRequest.SerializeToString,
                response_deserializer=cosmos__pb2.TestCaseResponse.FromString,
                _registered_method=True)
        self.GetTestCases = channel.unary_unary(
                '/cosmos.SandboxService/GetTestCases',
                request_serializer=cosmos__pb2.GetTestCasesRequest.SerializeToString,
                response_deserializer=cosmos__pb2.GetTestCasesResponse.FromString,
                _registered_method=True)
        self.StartRun = channel.unary_unary(
                '/cosmos.SandboxService/StartRun',
                request_serializer=cosmos__pb2.StartRunRequest.SerializeToString,
                response_deserializer=cosmos__pb2.RunResponse.FromString,
                _registered_method=True)
        self.RecordResult = channel.unary_unary(
                '/cosmos.SandboxService/RecordResult',
                request_serializer=cosmos__pb2.RecordResultRequest.SerializeToString,
                response_deserializer=cosmos__pb2.RecordResultResponse.FromString,
                _registered_method=True)
        self.CompleteRun = channel.unary_unary(
                '/cosmos.SandboxService/CompleteRun',
                request_serializer=cosmos__pb2.CompleteRunRequest.SerializeToString,
                response_deserializer=cosmos__pb2.RunResponse.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/cosmos.SandboxService/GetRun',
                request_serializer=cosmos__pb2.GetRunRequest.SerializeToString,
                response_deserializer=cosmos__pb2.RunResponse.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/cosmos.SandboxService/ListRuns',
                request_serializer=cosmos__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=cosmos__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.CompareRuns = channel.unary_unary(
                '/cosmos.SandboxService/CompareRuns',
                request_serializer=cosmos__pb2.CompareRunsRequest.SerializeToString,
                response_deserializer=cosmos__pb2.CompareResponse.FromString,
                _registered_method=True)
        self.RunEvaluationStream = channel.unary_stream(
                '/cosmos.SandboxService/RunEvaluationStream',
                request_serializer=cosmos__pb2.StartRunRequest.SerializeToString,
                response_deserializer=cosmos__pb2.EvalProgress.FromString,
                _registered_method=True)


class SandboxServiceServicer(object):
    """============================================================
    Sandbox Service (Evaluation)
    ============================================================

    """

    def CreateSuite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSuites(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTestCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTestCases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompareRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunEvaluationStream(self, request, context):
        """Stream live test results as they execute
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSuite': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSuite,
                    request_deserializer=cosmos__pb2.CreateSuiteRequest.FromString,
                    response_serializer=cosmos__pb2.SuiteResponse.SerializeToString,
            ),
            'ListSuites': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSuites,
                    request_deserializer=cosmos__pb2.ListSuitesRequest.FromString,
                    response_serializer=cosmos__pb2.ListSuitesResponse.SerializeToString,
            ),
            'AddTestCase': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTestCase,
                    request_deserializer=cosmos__pb2.AddTestCaseRequest.FromString,
                    response_serializer=cosmos__pb2.TestCaseResponse.SerializeToString,
            ),
            'GetTestCases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTestCases,
                    request_deserializer=cosmos__pb2.GetTestCasesRequest.FromString,
                    response_serializer=cosmos__pb2.GetTestCasesResponse.SerializeToString,
            ),
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=cosmos__pb2.StartRunRequest.FromString,
                    response_serializer=cosmos__pb2.RunResponse.SerializeToString,
            ),
            'RecordResult': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordResult,
                    request_deserializer=cosmos__pb2.RecordResultRequest.FromString,
                    response_serializer=cosmos__pb2.RecordResultResponse.SerializeToString,
            ),
            'CompleteRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteRun,
                    request_deserializer=cosmos__pb2.CompleteRunRequest.FromString,
                    response_serializer=cosmos__pb2.RunResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=cosmos__pb2.GetRunRequest.FromString,
                    response_serializer=cosmos__pb2.RunResponse.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=cosmos__pb2.ListRunsRequest.FromString,
                    response_serializer=cosmos__pb2.ListRunsResponse.SerializeToString,
            ),
            'CompareRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareRuns,
                    request_deserializer=cosmos__pb2.CompareRunsRequest.FromString,
                    response_serializer=cosmos__pb2.CompareResponse.SerializeToString,
            ),
            'RunEvaluationStream': grpc.unary_stream_rpc_method_handler(
                    servicer.RunEvaluationStream,
                    request_deserializer=cosmos__pb2.StartRunRequest.FromString,
                    response_serializer=cosmos__pb2.EvalProgress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cosmos.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cosmos.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService(object):
    """============================================================
    Sandbox Service (Evaluation)
    ============================================================

    """

    @staticmethod
    def CreateSuite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.SandboxService/CreateSuite',
            cosmos__pb2.CreateSuiteRequest.SerializeToString,
            cosmos__pb2.SuiteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSuites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.SandboxService/ListSuites',
            cosmos__pb2.ListSuitesRequest.SerializeToString,
            cosmos__pb2.ListSuitesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTestCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.SandboxService/AddTestCase',
            cosmos__pb2.AddTestCaseRequest.SerializeToString,
            cosmos__pb2.TestCaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTestCases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.SandboxService/GetTestCases',
            cosmos__pb2.GetTestCasesRequest.SerializeToString,
            cosmos__pb2.GetTestCasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.SandboxService/StartRun',
            cosmos__pb2.StartRunRequest.SerializeToString,
            cosmos__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.SandboxService/RecordResult',
            cosmos__pb2.RecordResultRequest.SerializeToString,
            cosmos__pb2.RecordResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.SandboxService/CompleteRun',
            cosmos__pb2.CompleteRunRequest.SerializeToString,
            cosmos__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.SandboxService/GetRun',
            cosmos__pb2.GetRunRequest.SerializeToString,
            cosmos__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.SandboxService/ListRuns',
            cosmos__pb2.ListRunsRequest.SerializeToString,
            cosmos__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompareRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.SandboxService/CompareRuns',
            cosmos__pb2.CompareRunsRequest.SerializeToString,
            cosmos__pb2.CompareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunEvaluationStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cosmos.SandboxService/RunEvaluationStream',
            cosmos__pb2.StartRunRequest.SerializeToString,
            cosmos__pb2.EvalProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TrainingServiceStub(object):
    """============================================================
    Training Service
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerEmbeddingTraining = channel.unary_unary(
                '/cosmos.TrainingService/TriggerEmbeddingTraining',
                request_serializer=cosmos__pb2.TrainingRequest.SerializeToString,
                response_deserializer=cosmos__pb2.TrainingJobResponse.FromString,
                _registered_method=True)
        self.TriggerIntentTraining = channel.unary_unary(
                '/cosmos.TrainingService/TriggerIntentTraining',
                request_serializer=cosmos__pb2.TrainingRequest.SerializeToString,
                response_deserializer=cosmos__pb2.TrainingJobResponse.FromString,
                _registered_method=True)
        self.TriggerGraphWeightOptimization = channel.unary_unary(
                '/cosmos.TrainingService/TriggerGraphWeightOptimization',
                request_serializer=cosmos__pb2.TrainingRequest.SerializeToString,
                response_deserializer=cosmos__pb2.TrainingJobResponse.FromString,
                _registered_method=True)
        self.GetTrainingStatus = channel.unary_unary(
                '/cosmos.TrainingService/GetTrainingStatus',
                request_serializer=cosmos__pb2.GetJobRequest.SerializeToString,
                response_deserializer=cosmos__pb2.TrainingJobResponse.FromString,
                _registered_method=True)
        self.ListTrainingJobs = channel.unary_unary(
                '/cosmos.TrainingService/ListTrainingJobs',
                request_serializer=cosmos__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=cosmos__pb2.ListJobsResponse.FromString,
                _registered_method=True)
        self.WatchTrainingJob = channel.unary_stream(
                '/cosmos.TrainingService/WatchTrainingJob',
                request_serializer=cosmos__pb2.GetJobRequest.SerializeToString,
                response_deserializer=cosmos__pb2.TrainingProgress.FromString,
                _registered_method=True)


class TrainingServiceServicer(object):
    """============================================================
    Training Service
    ============================================================

    """

    def TriggerEmbeddingTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerIntentTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerGraphWeightOptimization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTrainingJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchTrainingJob(self, request, context):
        """Stream training progress live
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerEmbeddingTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerEmbeddingTraining,
                    request_deserializer=cosmos__pb2.TrainingRequest.FromString,
                    response_serializer=cosmos__pb2.TrainingJobResponse.SerializeToString,
            ),
            'TriggerIntentTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerIntentTraining,
                    request_deserializer=cosmos__pb2.TrainingRequest.FromString,
                    response_serializer=cosmos__pb2.TrainingJobResponse.SerializeToString,
            ),
            'TriggerGraphWeightOptimization': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerGraphWeightOptimization,
                    request_deserializer=cosmos__pb2.TrainingRequest.FromString,
                    response_serializer=cosmos__pb2.TrainingJobResponse.SerializeToString,
            ),
            'GetTrainingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingStatus,
                    request_deserializer=cosmos__pb2.GetJobRequest.FromString,
                    response_serializer=cosmos__pb2.TrainingJobResponse.SerializeToString,
            ),
            'ListTrainingJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTrainingJobs,
                    request_deserializer=cosmos__pb2.ListJobsRequest.FromString,
                    response_serializer=cosmos__pb2.ListJobsResponse.SerializeToString,
            ),
            'WatchTrainingJob': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchTrainingJob,
                    request_deserializer=cosmos__pb2.GetJobRequest.FromString,
                    response_serializer=cosmos__pb2.TrainingProgress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cosmos.TrainingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cosmos.TrainingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainingService(object):
    """============================================================
    Training Service
    ============================================================

    """

    @staticmethod
    def TriggerEmbeddingTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.TrainingService/TriggerEmbeddingTraining',
            cosmos__pb2.TrainingRequest.SerializeToString,
            cosmos__pb2.TrainingJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerIntentTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.TrainingService/TriggerIntentTraining',
            cosmos__pb2.TrainingRequest.SerializeToString,
            cosmos__pb2.TrainingJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerGraphWeightOptimization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.TrainingService/TriggerGraphWeightOptimization',
            cosmos__pb2.TrainingRequest.SerializeToString,
            cosmos__pb2.TrainingJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.TrainingService/GetTrainingStatus',
            cosmos__pb2.GetJobRequest.SerializeToString,
            cosmos__pb2.TrainingJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTrainingJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.TrainingService/ListTrainingJobs',
            cosmos__pb2.ListJobsRequest.SerializeToString,
            cosmos__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchTrainingJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cosmos.TrainingService/WatchTrainingJob',
            cosmos__pb2.GetJobRequest.SerializeToString,
            cosmos__pb2.TrainingProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
