"""
Hybrid Chat API — Two-stage parallel probe + conditional deepening.

POST /cosmos/api/v1/hybrid/chat          — Full hybrid response
POST /cosmos/api/v1/hybrid/chat/stream   — SSE streaming with pipeline events
GET  /cosmos/api/v1/hybrid/analytics     — Pipeline attribution analytics
"""

import asyncio
import json
import time
from uuid import UUID, uuid4
from typing import Optional, Dict, Any

import structlog
from fastapi import APIRouter, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from app.services.query_orchestrator import QueryOrchestrator, OrchestratorResult
from app.events.kafka_bus import QueryCompletedEvent

logger = structlog.get_logger()
router = APIRouter()


# ---------------------------------------------------------------------------
# Request / Response Models
# ---------------------------------------------------------------------------

class HybridChatRequest(BaseModel):
    session_id: Optional[UUID] = None
    message: str = Field(..., min_length=1, max_length=10000)
    user_id: str
    repo_id: Optional[str] = None
    role: Optional[str] = None
    company_id: Optional[str] = None
    channel: str = "web"
    debug: bool = False  # Include pipeline_breakdown in response
    metadata: dict = Field(default_factory=dict)
    # Pre-fetched by MARS from SSO — skips COSMOS internal SSO login.
    # MARS simulation flow: MARS fetches seller token → passes here →
    # COSMOS uses it directly for live Shiprocket API calls (act mode).
    seller_token: Optional[str] = None
    sso_token: Optional[str] = None   # alias, same token different name
    # ICRM admin token — generated by MARS on MCP session create from user_sso_tokens DB.
    # Used for /v1/admin/* and /api/v1/admin/* endpoints (requires company_id=1 role).
    icrm_token: Optional[str] = None
    tournament_mode: bool = False     # A/B strategy testing via TournamentEngine
    # Write action approval gate (M3-P1 #22)
    # confirm_action=True + confirm_token=<token> re-executes a pending write action.
    confirm_action: bool = False
    confirm_token: Optional[str] = None


class PipelineBreakdown(BaseModel):
    pipeline: str
    contributed: bool
    latency_ms: float
    items: int
    stages: list


class HybridChatResponse(BaseModel):
    session_id: UUID
    message_id: UUID
    content: str
    intents: list = Field(default_factory=list)
    confidence: float = 0.0
    needs_clarification: bool = False
    clarification_prompt: Optional[str] = None
    tools_used: list = Field(default_factory=list)
    # Attribution (only when debug=True)
    pipeline_breakdown: Optional[Dict[str, Any]] = None
    timing: Optional[Dict[str, float]] = None
    signal: Optional[Dict[str, Any]] = None
    wave_trace: Optional[Dict[str, Any]] = None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _get_orchestrator(request: Request) -> Optional[QueryOrchestrator]:
    return getattr(request.app.state, "query_orchestrator", None)


def _get_react_engine(request: Request):
    return getattr(request.app.state, "react_engine", None)


def _get_tournament_engine(request: Request):
    return getattr(request.app.state, "tournament_engine", None)


def _get_approval_gate(request: Request):
    return getattr(request.app.state, "action_approval_gate", None)


def _get_event_bus(request: Request):
    return getattr(request.app.state, "event_bus", None)


def _build_llm_context(orch_result: OrchestratorResult) -> str:
    """Format orchestrator context into a text prompt for the LLM."""
    parts = []

    # Intents
    if orch_result.intents:
        intents_str = ", ".join(
            f"{i.get('intent', '?')}({i.get('entity', '?')}, conf={i.get('confidence', 0):.2f})"
            for i in orch_result.intents
        )
        parts.append(f"[Intents] {intents_str}")

    ctx = orch_result.context

    # Entity
    entity = ctx.get("entity", {})
    if entity:
        eid = entity.get("entity_id") or "unknown"
        uid = entity.get("user_id") or "unknown"
        parts.append(f"[Entity] entity_id={eid}, user_id={uid}")

    # Knowledge chunks from vector search
    chunks = ctx.get("knowledge_chunks", [])
    if chunks:
        parts.append(f"[Knowledge Base — {len(chunks)} relevant chunks]")
        for i, chunk in enumerate(chunks[:5]):
            content = chunk.get("content", "")[:300]
            sim = chunk.get("similarity", 0)
            parts.append(f"  Chunk {i+1} (sim={sim:.2f}): {content}")

    # Graph traversal paths
    graph = ctx.get("graph_traversal", {})
    traversals = graph.get("traversals", [])
    if traversals:
        parts.append(f"[Graph Traversal — {len(traversals)} paths]")
        for t in traversals:
            if "formatted_context" in t:
                parts.append(f"  {t['formatted_context'][:500]}")
            else:
                nodes = t.get("nodes", [])
                edges = t.get("edges", [])
                path_str = " → ".join(
                    f"{n.get('label', n.get('id', '?'))}({n.get('type', '?')})"
                    for n in nodes[:6]
                )
                parts.append(f"  From {t.get('start_node', '?')}: {path_str}")
                if len(nodes) > 6:
                    parts.append(f"    ... +{len(nodes)-6} more nodes, {len(edges)} edges")

    # Page context
    page_ctx = ctx.get("page_context", {})
    pages = page_ctx.get("pages", [])
    if pages:
        parts.append(f"[Page Context — {len(pages)} matching pages]")
        for p in pages[:3]:
            parts.append(
                f"  {p.get('page_id', '?')} | route={p.get('route', '?')} | "
                f"domain={p.get('domain', '?')} | roles={p.get('roles_required', [])}"
            )
        role_access = page_ctx.get("role_access")
        if role_access is not None:
            parts.append(f"  Role access: {'granted' if role_access else 'DENIED'}")

    # Cross-repo
    cross = ctx.get("cross_repo_comparison", {})
    if cross and cross.get("shared_fields"):
        parts.append("[Cross-Repo Comparison]")
        parts.append(f"  Source: {cross.get('source', {}).get('page_id', '?')} ({cross.get('source', {}).get('field_count', 0)} fields)")
        parts.append(f"  Target: {cross.get('target', {}).get('page_id', '?')} ({cross.get('target', {}).get('field_count', 0)} fields)")
        parts.append(f"  Shared fields: {', '.join(cross.get('shared_fields', [])[:10])}")
        target_only = cross.get("target_only_fields", [])
        if target_only:
            parts.append(f"  Target-only fields (admin has, seller doesn't): {', '.join(target_only[:10])}")
    elif ctx.get("cross_repo_alias", {}).get("mapping"):
        mapping = ctx["cross_repo_alias"]["mapping"]
        parts.append(f"[Cross-Repo Alias] {mapping}")

    # Session history
    session = ctx.get("session_history", {})
    recent = session.get("recent_entities", [])
    if recent:
        parts.append(f"[Session History — {len(recent)} recent entities]")
        for e in recent[:3]:
            parts.append(f"  {e.get('label', e.get('id', '?'))}")

    # Phase 2: Field traces (deterministic field → API → DB column)
    field_traces = ctx.get("field_traces", [])
    if field_traces:
        parts.append(f"[Field Traces — {len(field_traces)} traces]")
        for ft in field_traces[:5]:
            if isinstance(ft, dict):
                field_name = ft.get("field_name", ft.get("field", "?"))
                api = ft.get("api_endpoint", ft.get("api", "?"))
                col = ft.get("db_column", ft.get("column", ""))
                line = f"  {field_name} → {api}"
                if col:
                    line += f" → {col}"
                parts.append(line)

    # Phase 2: Neighbor chunks (sibling evidence from same parent document)
    neighbor_chunks = ctx.get("neighbor_chunks", [])
    if neighbor_chunks:
        parts.append(f"[Neighbor Chunks — {len(neighbor_chunks)} sibling chunks]")
        for nc in neighbor_chunks[:3]:
            chunk_type = nc.get("chunk_type", "")
            content = nc.get("content", "")[:200]
            section = nc.get("section", "")
            label = f"{chunk_type}/{section}" if section else chunk_type
            parts.append(f"  [{label}] {content}")

    # Phase 2: Module context (module_doc vector + graph node unified)
    module_context = ctx.get("module_context", {})
    if module_context:
        parts.append(f"[Module Context — {len(module_context)} module(s)]")
        for mod_name, mod_data in list(module_context.items())[:3]:
            if isinstance(mod_data, dict):
                parts.append(f"  [{mod_name}]")
                for sec in mod_data.get("sections", [])[:2]:
                    parts.append(f"    {str(sec)[:200]}")
                edges = mod_data.get("graph_edges", [])
                if edges:
                    parts.append(f"    edges: {', '.join(edges[:4])}")

    # Wave 3: LangGraph reasoning trace + refined entities
    w3 = ctx.get("wave3_reasoning", {})
    if w3:
        refined = w3.get("refined_entities", [])
        tool_plan = w3.get("tool_plan", [])
        trace = w3.get("reasoning_trace", "")
        if refined:
            parts.append(f"[Wave 3 — LangGraph Refined Entities ({len(refined)})]")
            for ent in refined[:6]:
                parts.append(f"  {ent.get('type', '?')}={ent.get('value', '?')}")
        if tool_plan:
            parts.append(f"[Wave 3 — Suggested Tools: {', '.join(str(t) for t in tool_plan[:5])}]")
        if trace:
            parts.append(f"[Wave 3 — Reasoning] {trace[:300]}")

    # Wave 4: Neo4j targeted graph paths
    w4 = ctx.get("wave4_graph", {})
    if w4 and w4.get("path_count", 0) > 0:
        rel_ctx = w4.get("relationship_context", "")
        parts.append(
            f"[Wave 4 — Neo4j Graph ({w4['path_count']} nodes, "
            f"{w4.get('entity_targets_used', 0)} entity targets)]"
        )
        if rel_ctx:
            parts.append(rel_ctx[:500])

    return "\n".join(parts) if parts else "[No context gathered from pipelines]"


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.post("/chat", response_model=HybridChatResponse)
async def hybrid_chat(request: Request, chat_req: HybridChatRequest):
    """
    Hybrid chat: parallel probe all 5 pipelines, conditionally deepen,
    then assemble answer via LLM. Returns attribution when debug=True.
    """
    orchestrator = _get_orchestrator(request)
    session_id = chat_req.session_id or uuid4()

    if orchestrator is None:
        return HybridChatResponse(
            session_id=session_id,
            message_id=uuid4(),
            content="[COSMOS] Hybrid orchestrator not initialized.",
        )

    # Read effective workflow settings from cache
    _settings_cache = getattr(request.app.state, "settings_cache", None)
    _workflow_settings = _settings_cache.get() if _settings_cache else None

    # ---------------------------------------------------------------
    # PRE-EXECUTION GUARDRAILS (15 guards: injection, access, rate, cost)
    # ---------------------------------------------------------------
    react_engine = _get_react_engine(request)
    if react_engine and react_engine.guardrails:
        try:
            pre_context = {
                "query": chat_req.message,
                "user_id": chat_req.user_id,
                "company_id": chat_req.company_id,
                "role": chat_req.role,
                "channel": chat_req.channel,
                "session_id": str(session_id),
            }
            pre_result = await react_engine.guardrails.run_pre(pre_context)
            if pre_result.action.value == "block":
                return HybridChatResponse(
                    session_id=session_id,
                    message_id=uuid4(),
                    content=pre_result.reason or "Your request was blocked by safety checks.",
                    confidence=0.0,
                )
        except Exception as guard_err:
            logger.warning("hybrid_chat.pre_guardrail_error", error=str(guard_err))

    # Tournament mode: A/B test retrieval strategies via TournamentEngine,
    # then publish winner to Kafka so MARS quality dashboard captures it.
    if chat_req.tournament_mode:
        tournament = _get_tournament_engine(request)
        react_engine = _get_react_engine(request)
        if tournament is not None and react_engine is not None:
            return await _handle_hybrid_tournament(request, chat_req, session_id, react_engine, tournament)

    # Resolve seller token: prefer pre-fetched token from MARS (avoids duplicate SSO login),
    # fall back to sso_token alias, then let orchestrator fetch its own via SSO client.
    effective_seller_token = chat_req.seller_token or chat_req.sso_token or None

    # Run two-stage pipeline
    orch_result = await orchestrator.execute(
        query=chat_req.message,
        user_id=chat_req.user_id,
        repo_id=chat_req.repo_id,
        role=chat_req.role,
        company_id=chat_req.company_id or None,
        session_context=chat_req.metadata,
        session_id=str(session_id),
        workflow_settings=_workflow_settings,
        seller_token=effective_seller_token,
        icrm_token=chat_req.icrm_token,
    )

    # If we need clarification, return early
    if orch_result.needs_clarification:
        resp = HybridChatResponse(
            session_id=session_id,
            message_id=uuid4(),
            content=orch_result.clarification_prompt or "Could you provide more details?",
            intents=[i for i in orch_result.intents],
            needs_clarification=True,
            clarification_prompt=orch_result.clarification_prompt,
        )
        if chat_req.debug:
            attribution = orchestrator.to_attribution_summary(orch_result)
            resp.pipeline_breakdown = attribution["pipeline_breakdown"]
            resp.timing = attribution["timing"]
            resp.signal = attribution["signal"]
        return resp

    # ---------------------------------------------------------------
    # Stage 3: LLM Assembly via RIPER (MARS pattern #3)
    # COMPLEX → full RIPER, STANDARD → RIPER Lite, QUICK → direct
    # ---------------------------------------------------------------
    llm_context = _build_llm_context(orch_result)
    classification = orch_result.request_classification or {}
    complexity = classification.get("complexity", "standard")

    engine = _get_react_engine(request)
    content = ""
    confidence = 0.0
    tools_used = []
    llm_latency = 0.0

    # Check if fast-path already produced a result (Tier 0)
    fast_path_response = (orch_result.context or {}).get("fast_path_response")
    if fast_path_response:
        content = fast_path_response
        confidence = (orch_result.response_metadata or {}).get("confidence", 0.9)
        tools_used = (orch_result.response_metadata or {}).get("tools_used", [])
        llm_latency = (orch_result.response_metadata or {}).get("latency_ms", 0)

    elif orchestrator.riper_engine:
        # RIPER routing by complexity tier:
        #   COMPLEX → Full RIPER (R+I+P+E+R, 30s budget)
        #   STANDARD → RIPER Lite (R+P+E+R, 15s) with pillar hints from query intelligence
        #   QUICK → RIPER Lite with tighter 8s budget (entity lookups, schema queries)
        t0 = time.monotonic()
        try:
            if complexity == "complex":
                riper_result = await asyncio.wait_for(
                    orchestrator.riper_engine.process_full(
                        query=chat_req.message,
                        context=orch_result.context,
                        intents=orch_result.intents,
                    ),
                    timeout=30.0,
                )
            elif complexity == "standard":
                # Inject pillar hints from query intelligence so RIPER Research phase
                # focuses on the right KB pillar instead of scanning all chunks.
                riper_ctx = dict(orch_result.context or {})
                _qintel = getattr(orchestrator, "_query_intel", {}) or {}
                if _qintel.get("target_pillars"):
                    riper_ctx["pillar_hints"] = _qintel["target_pillars"]
                if _qintel.get("intent"):
                    riper_ctx["query_intent"] = _qintel["intent"]
                riper_result = await asyncio.wait_for(
                    orchestrator.riper_engine.process_lite(
                        query=chat_req.message,
                        context=riper_ctx,
                        intents=orch_result.intents,
                    ),
                    timeout=15.0,
                )
            else:
                # QUICK: RIPER Lite with tight timeout — simple entity lookups
                # don't benefit from long reasoning phases
                riper_result = await asyncio.wait_for(
                    orchestrator.riper_engine.process_lite(
                        query=chat_req.message,
                        context=orch_result.context,
                        intents=orch_result.intents,
                    ),
                    timeout=8.0,
                )

            llm_latency = (time.monotonic() - t0) * 1000
            content = riper_result.final_response
            confidence = riper_result.confidence
            tools_used = riper_result.tools_used
            orch_result.riper_summary = orchestrator.riper_engine.to_summary(riper_result)

        except (asyncio.TimeoutError, Exception) as riper_err:
            # Circuit breaker: RIPER/LLM failed → fall back to tool-only response
            llm_latency = (time.monotonic() - t0) * 1000
            logger.warning("hybrid_chat.riper_failed",
                           error=str(riper_err), latency_ms=round(llm_latency, 1))

            # Build tool-only response from orchestrator context
            ctx = orch_result.context or {}
            tool_data = ctx.get("multi_agent_response") or ctx.get("fast_path_response")
            if tool_data:
                content = tool_data
                confidence = 0.6
            else:
                # Last resort: use KB chunks directly
                chunks = ctx.get("knowledge_chunks", [])
                if chunks:
                    content = "Based on available information: " + " ".join(
                        c.get("content", "")[:200] for c in chunks[:3]
                    )
                    confidence = 0.4
                else:
                    content = "I'm having trouble processing this request. Please try again or rephrase your question."
                    confidence = 0.2

    elif engine is not None:
        # Fallback: direct ReAct (only if RIPER unavailable)
        augmented_context = {
            "user_id": chat_req.user_id,
            "company_id": chat_req.company_id,
            "channel": chat_req.channel,
            "pipeline_context": llm_context,
        }
        augmented_context.update(chat_req.metadata)
        t0 = time.monotonic()
        result = await engine.process(chat_req.message, augmented_context)
        llm_latency = (time.monotonic() - t0) * 1000
        content = result.response
        confidence = result.confidence
        tools_used = result.tools_used
    else:
        content = f"Based on pipeline analysis:\n\n{llm_context}"
        confidence = 0.5

    # ---------------------------------------------------------------
    # Agent Forge (MARS pattern #5) — if confidence < 60%, forge
    # ---------------------------------------------------------------
    if confidence < 0.6 and orchestrator.agent_forge:
        forge_result = await orchestrator.agent_forge.forge_and_execute(
            query=chat_req.message,
            intent=orch_result.intents[0].get("intent", "unknown") if orch_result.intents else "unknown",
            entity=orch_result.intents[0].get("entity", "unknown") if orch_result.intents else "unknown",
            context=orch_result.context,
        )
        if forge_result.response and forge_result.confidence > confidence:
            content = forge_result.response
            confidence = forge_result.confidence
            orch_result.forge_summary = {
                "forged": forge_result.forged,
                "reused": forge_result.reused,
                "agent_name": forge_result.agent.name if forge_result.agent else None,
                "agent_capability": forge_result.agent.capability.value if forge_result.agent else None,
                "latency_ms": round(forge_result.latency_ms, 1),
            }

    # ---------------------------------------------------------------
    # Stage 4: RALPH Self-Correction (MARS pattern #4)
    # ---------------------------------------------------------------
    if orchestrator.ralph_engine and content:
        ralph_result = await orchestrator.ralph_engine.evaluate(
            query=chat_req.message,
            response=content,
            confidence=confidence,
            intents=orch_result.intents,
            context=orch_result.context,
            tools_used=tools_used,
        )
        orch_result.ralph_summary = orchestrator.ralph_engine.to_summary(ralph_result)

        if ralph_result.improved_response:
            content = ralph_result.improved_response

        if ralph_result.verdict.value == "escalate":
            confidence = min(confidence, 0.3)

    # ---------------------------------------------------------------
    # PATTERN LEARNING: Record every successful resolution
    # Builds pattern confidence over time (30+ successes → fast path)
    # ---------------------------------------------------------------
    if content and confidence >= 0.5 and tools_used:
        try:
            intent_for_cache = "unknown"
            entity_for_cache = "unknown"
            if orch_result.intents:
                i0 = orch_result.intents[0]
                intent_for_cache = i0.get("intent", "unknown") if isinstance(i0, dict) else str(i0)
                entity_for_cache = i0.get("entity", "unknown") if isinstance(i0, dict) else "unknown"

            tool_seq = [{"tool_name": t} for t in tools_used]
            await orchestrator.pattern_cache.record_success(
                query=chat_req.message,
                intent=intent_for_cache,
                entity_type=entity_for_cache,
                tool_sequence=tool_seq,
                repo_id=chat_req.repo_id if hasattr(chat_req, 'repo_id') else "",
                role=chat_req.role if hasattr(chat_req, 'role') else "",
                latency_ms=llm_latency,
            )
        except Exception:
            pass  # non-critical

    # ---------------------------------------------------------------
    # POST-EXECUTION GUARDRAILS (10 guards: PII mask, leakage, hallucination, legal)
    # ---------------------------------------------------------------
    if react_engine and react_engine.guardrails and content:
        try:
            post_context = {
                "query": chat_req.message,
                "response": content,
                "user_id": chat_req.user_id,
                "company_id": chat_req.company_id,
                "role": chat_req.role,
                "tools_used": tools_used,
                "confidence": confidence,
                "intents": orch_result.intents,
                "context": orch_result.context,
            }
            post_result = await react_engine.guardrails.run_post(post_context)
            if post_result.action.value == "block":
                content = post_result.reason or "Response blocked by safety checks. Please contact support."
                confidence = 0.0
            elif post_result.action.value == "mask" and post_result.modified_data:
                content = post_result.modified_data  # PII-masked version
        except Exception as guard_err:
            logger.warning("hybrid_chat.post_guardrail_error", error=str(guard_err))

    # ---------------------------------------------------------------
    # Confidence-based response quality control
    # ---------------------------------------------------------------
    needs_clarification = False
    if confidence < 0.3 and content:
        # Very low confidence — system doesn't have reliable information
        content = (
            "I don't have enough reliable information to answer this question accurately. "
            "Please provide more details (like order ID, AWB number, or specific page name), "
            "or contact the support team for assistance."
        )
        needs_clarification = True
        logger.info("hybrid_chat.low_confidence_idk", query=chat_req.message[:80],
                     confidence=confidence)
    elif 0.3 <= confidence < 0.6 and content:
        # Medium confidence — prefix with uncertainty marker
        content = f"Based on available information (confidence: {confidence:.0%}): {content}"

    # ---------------------------------------------------------------
    # Build response
    # ---------------------------------------------------------------
    resp = HybridChatResponse(
        session_id=session_id,
        message_id=uuid4(),
        content=content,
        intents=orch_result.intents,
        confidence=confidence,
        needs_clarification=needs_clarification,
        tools_used=tools_used,
    )

    if chat_req.debug:
        attribution = orchestrator.to_attribution_summary(orch_result)
        resp.pipeline_breakdown = attribution["pipeline_breakdown"]
        resp.timing = {
            **attribution["timing"],
            "llm_ms": round(llm_latency, 1),
        }
        resp.signal = attribution["signal"]
        # Include MARS integration summaries
        if orch_result.request_classification:
            resp.pipeline_breakdown["_request_classification"] = orch_result.request_classification
        if orch_result.riper_summary:
            resp.pipeline_breakdown["_riper"] = orch_result.riper_summary
        if orch_result.ralph_summary:
            resp.pipeline_breakdown["_ralph"] = orch_result.ralph_summary
        if orch_result.forge_summary:
            resp.pipeline_breakdown["_agent_forge"] = orch_result.forge_summary
        if orch_result.wave3_context:
            resp.pipeline_breakdown["_wave3_langgraph"] = orch_result.wave3_context
        if orch_result.wave4_context:
            resp.pipeline_breakdown["_wave4_neo4j"] = orch_result.wave4_context

        # Canonical Wave Trace — stable schema for MARS proxy / LIME frontend.
        # Pass `attribution` explicitly so wave_trace can read the real
        # pipeline_breakdown and signal dicts instead of reading non-existent
        # attributes from OrchestratorResult (which caused pb/signal to be always {}).
        try:
            from app.services.wave_trace import build_wave_trace
            resp.wave_trace = build_wave_trace(
                orch_result=orch_result,
                query=chat_req.message,
                content=content,
                confidence=confidence,
                tools_used=tools_used,
                timing=resp.timing,
                user_id=chat_req.user_id or "",
                company_id=chat_req.company_id or "",
                role=chat_req.role or "",
                source=chat_req.metadata.get("source", "simulation") if isinstance(chat_req.metadata, dict) else "simulation",
                attribution=attribution,  # Phase A fix: pass real attribution dict
            )
        except Exception as trace_err:
            logger.warning("hybrid_chat.wave_trace_error", error=str(trace_err))

    # Low-confidence feedback loop: persist traces for auto-learning
    try:
        from app.services.feedback_loop import FeedbackLoop
        cls_domain = (orch_result.request_classification or {}).get("domain", "")
        await FeedbackLoop.maybe_persist(
            orch_result=orch_result,
            query=chat_req.message,
            confidence=confidence,
            tools_used=tools_used,
            query_mode=getattr(orch_result, '_query_mode', 'lookup'),
            domain=cls_domain,
        )
    except Exception:
        pass  # feedback loop is best-effort

    # Publish execution event to RabbitMQ for MARS analytics
    try:
        from app.events.rabbitmq_producer import cosmos_event_producer
        wave_trace_data = resp.wave_trace if hasattr(resp, 'wave_trace') else None
        await cosmos_event_producer.publish_query_trace(
            trace_id=str(resp.message_id),
            query=chat_req.message,
            user_id=chat_req.user_id,
            company_id=chat_req.company_id or "",
            agent_name=(orch_result.response_metadata or {}).get("agent", ""),
            query_mode=getattr(orch_result, '_query_mode', 'lookup'),
            confidence=confidence,
            tools_used=tools_used,
            wave_trace=wave_trace_data,
            classification=orch_result.request_classification,
            latency_ms=orch_result.total_latency_ms,
            source=chat_req.metadata.get("source", "icrm") if isinstance(chat_req.metadata, dict) else "icrm",
        )
    except Exception:
        pass  # event publishing is best-effort

    # Publish to Kafka (stage-cosmos-query-trace) — wave-level detail for MARS
    # quality dashboard, internal tooling, and tournament eval.
    # wave_trace.waves[] contains all 5 waves with full per-wave diagnostics.
    try:
        bus = _get_event_bus(request)
        if bus is not None:
            wave_trace_list = None
            if resp.wave_trace and isinstance(resp.wave_trace, dict):
                wave_trace_list = resp.wave_trace.get("waves")
            classification = orch_result.request_classification or {}
            kafka_event = QueryCompletedEvent(
                session_id=str(session_id),
                user_id=chat_req.user_id or "",
                company_id=chat_req.company_id or "",
                query=chat_req.message,
                intent=classification.get("domain", "unknown"),
                entity=classification.get("entity", "unknown"),
                confidence=confidence,
                tools_used=tools_used,
                response=content,
                escalated=confidence < 0.3,
                latency_ms=orch_result.total_latency_ms,
                model="claude-opus-4-6",
                tokens_in=0,
                tokens_out=0,
                cost_usd=0.0,
                wave_trace=wave_trace_list,
            )
            await bus.produce_query_completed(kafka_event)
    except Exception:
        pass  # kafka publish is best-effort

    return resp


async def _handle_hybrid_tournament(
    request: Request,
    chat_req: "HybridChatRequest",
    session_id,
    react_engine,
    tournament_engine,
) -> "HybridChatResponse":
    """Run query through TournamentEngine and publish winner to Kafka.

    Uses react_engine.classifier for intent/entity resolution, runs the
    tournament, then emits a QueryCompletedEvent so the MARS quality
    dashboard and internal eval tooling capture the result — same as
    the standard /chat tournament path.
    """
    classification = react_engine.classifier.classify(chat_req.message)
    tournament_result = await tournament_engine.run(
        query=chat_req.message,
        intent=classification.intent.value,
        entity=classification.entity.value,
        entity_id=classification.entity_id,
    )

    if tournament_result.winner:
        content = tournament_result.winner.answer
        confidence = tournament_result.winner.confidence
        tools_used = [tournament_result.winner.strategy.value]
    else:
        content = "[COSMOS] Tournament produced no winning strategy."
        confidence = 0.0
        tools_used = []

    # Publish to Kafka so quality dashboard captures tournament runs
    try:
        bus = _get_event_bus(request)
        if bus is not None:
            kafka_event = QueryCompletedEvent(
                session_id=str(session_id),
                user_id=chat_req.user_id or "",
                company_id=chat_req.company_id or "",
                query=chat_req.message,
                intent=classification.intent.value,
                entity=classification.entity.value,
                confidence=confidence,
                tools_used=tools_used,
                response=content,
                escalated=confidence < 0.3,
                latency_ms=0.0,
                model="tournament",
                tokens_in=0,
                tokens_out=0,
                cost_usd=0.0,
                wave_trace=None,
            )
            await bus.produce_query_completed(kafka_event)
    except Exception:
        pass

    return HybridChatResponse(
        session_id=session_id,
        message_id=uuid4(),
        content=content,
        confidence=confidence,
        tools_used=tools_used,
    )


@router.get("/chat/trace_schema")
async def get_trace_schema():
    """
    GET /cosmos/api/v1/hybrid/chat/trace_schema

    Returns the canonical wave_trace JSON schema with an annotated example.
    Use this as a reference for frontend parsing — the schema is stable across
    COSMOS versions.  Debug responses return wave_trace at the same shape.
    """
    example_wave = {
        "wave": 1,
        "name": "string — wave display name",
        "status": "done | skipped | error | running",
        "latency_ms": 0.0,
        "skipped_reason": "null or string explaining why this wave was skipped",
        "summary": "string — human-readable one-line summary",
        "key_findings": {
            "__comment": "Wave-specific structured data. Always a dict.",
            "domain": "string — detected intent domain",
            "complexity": "quick | standard | complex",
            "confidence": 0.0,
            "entity_resolved": False,
            "evidence_count": 0,
            "pipelines": {"pipeline_name": {"found": True, "items": 0, "latency_ms": 0.0}},
        },
        "vector_trace": {
            "__comment": "Retrieval evidence. Always present; searched=False means no retrieval ran.",
            "searched": True,
            "top_score": 0.0,
            "top_results": [
                {
                    "doc_id": "string",
                    "content": "string (truncated to 200 chars)",
                    "similarity": 0.0,
                    "chunk_type": "api_overview | page_summary | module_summary | ...",
                    "parent_doc_id": "string — e.g. api_endpoint:MultiChannel_API:mcapi.v1.orders.get",
                    "entity_type": "string",
                    "trust_score": 0.0,
                }
            ],
            "total_chunks": 0,
            "threshold": 0.6,
            "chunk_types": ["list of distinct chunk_types in results"],
            "parent_doc_ids": ["list of distinct parent_doc_ids in results"],
        },
        "raw": "null or dict — full raw debug data for this wave",
    }
    schema = {
        "schema_version": "1.0",
        "description": "Canonical COSMOS 5-wave trace schema. Returned in debug responses as wave_trace.",
        "top_level_keys": {
            "trace_id": "UUID string",
            "query": "The original user query",
            "source": "simulation | icrm_live",
            "user_id": "string",
            "company_id": "string or null",
            "role": "string",
            "timestamp": "ISO 8601 UTC",
            "classification": {
                "domain": "string",
                "complexity": "quick | standard | complex",
                "mode": "string",
                "confidence": 0.0,
                "sub_domains": [],
            },
            "waves": ["Array of 5 wave objects (see wave_schema below). wave.wave = 1..5"],
            "response": {
                "content": "Final LLM response text",
                "confidence": 0.0,
                "tools_used": [],
                "agent_chain": [],
                "guardrails_pre": {"passed": 15, "blocked": 0},
                "guardrails_post": {"passed": 10, "masked": 0},
                "pattern_hit": False,
                "total_latency_ms": 0.0,
            },
            "metadata": {
                "fast_path": False,
                "multi_agent": False,
                "tiers_visited": [1],
                "wave3_enabled": False,
                "wave4_enabled": False,
            },
            "tenant_resolution": "dict or null",
        },
        "wave_schema": example_wave,
        "wave_names": {
            1: "Probe — intent, entity, vector, page, session",
            2: "Deep GraphRAG — 4-leg RRF, neighbor expand, module unify",
            3: "LangGraph — stateful reasoning, entity refinement",
            4: "Neo4j — targeted graph traversal from refined entities",
            5: "RIPER + ReAct — LLM execution, tools, RALPH verification",
        },
        "backward_compat": [
            "pipeline_breakdown — per-pipeline attribution (probe/deep stages)",
            "timing — {probe_ms, deep_ms, llm_ms, total_ms}",
            "signal — {total_items, relevant_items, signal_to_noise_pct}",
        ],
    }
    return schema


@router.post("/chat/stream")
async def hybrid_chat_stream(request: Request, chat_req: HybridChatRequest):
    """
    SSE streaming hybrid chat. Emits per-pipeline events so the frontend
    can show real-time progress through each stage.

    Events:
    - stage:probe_start     — Stage 1 starting
    - probe:{pipeline}      — Individual probe result
    - stage:probe_complete  — All probes done
    - stage:deep_start      — Stage 2 starting
    - deep:{pipeline}       — Individual deep result (or skipped)
    - stage:deep_complete   — Deep stage done
    - stage:llm_start       — LLM assembly starting
    - chunk                 — LLM response text chunks
    - attribution           — Full pipeline breakdown
    - done                  — Final metadata
    - error                 — Error information
    """
    orchestrator = _get_orchestrator(request)
    session_id = str(chat_req.session_id or uuid4())

    async def generate():
        try:
            if orchestrator is None:
                yield _sse("error", {"message": "Hybrid orchestrator not initialized"})
                return

            # --- Approval confirmation path (M3-P1 #22) ---
            # When the client re-sends with confirm_action=True + confirm_token,
            # skip the full pipeline and directly execute the pre-approved action.
            if chat_req.confirm_action and chat_req.confirm_token:
                gate = _get_approval_gate(request)
                if gate is None:
                    yield _sse("error", {"message": "Action approval gate not initialized"})
                    yield _sse("done", {"session_id": session_id, "confidence": 0.0, "intents": []})
                    return
                proposal = await gate.consume(chat_req.confirm_token)
                if proposal is None:
                    yield _sse("error", {
                        "message": "Confirmation token is invalid or has expired. Please re-submit the original request.",
                    })
                    yield _sse("done", {"session_id": session_id, "confidence": 0.0, "intents": []})
                    return
                # SECURITY: validate session ownership — prevent cross-session token reuse
                if proposal.session_id != str(session_id):
                    logger.warning(
                        "action_approval.session_mismatch",
                        proposal_session=proposal.session_id,
                        request_session=str(session_id),
                    )
                    yield _sse("error", {"message": "Confirmation token does not belong to this session."})
                    yield _sse("done", {"session_id": session_id, "confidence": 0.0, "intents": []})
                    return
                yield _sse("action_executing", {
                    "action": proposal.action_type,
                    "summary": proposal.summary,
                    "risk_level": proposal.risk_level,
                })
                try:
                    from app.config import settings as _settings
                    from app.services.tool_executor import ToolExecutorService, SessionContext as _SC
                    _executor = ToolExecutorService(settings=_settings, db=None)
                    _ctx = _SC(
                        seller_token=chat_req.seller_token,
                        icrm_token=chat_req.icrm_token,
                        approved=True,
                        approved_job_id=proposal.action_type,
                    )
                    exec_result = await _executor.execute(
                        proposal.action_type, proposal.action_input, _ctx
                    )
                    await _executor.aclose()
                except Exception as _exec_exc:
                    logger.error("action_approval.execute_error", error=str(_exec_exc))
                    yield _sse("error", {"message": f"Action execution failed: {str(_exec_exc)}"})
                    yield _sse("done", {"session_id": session_id, "confidence": 0.0, "intents": []})
                    return
                yield _sse("action_executed", {
                    "action": exec_result.tool_name,
                    "status": exec_result.status,
                    "data": exec_result.data,
                    "error": exec_result.error,
                    "latency_ms": round(exec_result.latency_ms, 1),
                })
                _ok = exec_result.status == "success"
                _summary_text = (
                    f"{proposal.summary} — executed successfully."
                    if _ok else
                    f"Action could not be completed: {exec_result.error or exec_result.status}"
                )
                yield _sse("chunk", {"text": _summary_text})
                yield _sse("done", {
                    "session_id": session_id,
                    "confidence": 1.0 if _ok else 0.0,
                    "tools_used": [exec_result.tool_name],
                    "intents": [],
                })
                return

            # Phase 5f: Wave progress queue — bridge between orchestrator callback
            # and SSE generator. The callback enqueues events; we drain them at
            # natural yield points so the client sees per-wave progress in real time.
            import asyncio as _asyncio
            _wave_queue: _asyncio.Queue = _asyncio.Queue()

            async def _on_wave_progress(wave_id, task_id, status, data):
                await _wave_queue.put({
                    "wave_id": wave_id,
                    "task_id": task_id,
                    "status": status,
                    **data,
                })

            async def _drain_wave_queue():
                """Yield all pending wave progress events from the queue."""
                while not _wave_queue.empty():
                    event = _wave_queue.get_nowait()
                    yield _sse(f"wave:{event['wave_id']}:{event['status']}", event)

            # --- Stage 1: Parallel Probe ---
            yield _sse("stage:probe_start", {"pipelines": [
                "intent_classifier", "entity_lookup", "vector_search",
                "page_role", "cross_repo",
            ]})

            probe_start = time.monotonic()
            # Phase 5f: inject wave progress callback so WaveExecutor emits events
            orchestrator._wave_progress_cb = _on_wave_progress
            probe_results = await orchestrator._stage1_parallel_probe(
                query=chat_req.message,
                user_id=chat_req.user_id,
                repo_id=chat_req.repo_id,
                role=chat_req.role,
                session_context=chat_req.metadata,
            )
            probe_ms = (time.monotonic() - probe_start) * 1000

            # Drain wave progress events from W1
            async for wave_event in _drain_wave_queue():
                yield wave_event

            # Emit individual probe results
            for pipeline, pr in probe_results.items():
                yield _sse(f"probe:{pipeline.value}", {
                    "found_data": pr.found_data,
                    "latency_ms": round(pr.latency_ms, 1),
                    "recommend_deepen": pr.recommend_deepen,
                    "reason": pr.reason,
                    "error": pr.error,
                })

            yield _sse("stage:probe_complete", {
                "latency_ms": round(probe_ms, 1),
                "pipelines_with_data": [
                    p.value for p, r in probe_results.items() if r.found_data
                ],
            })

            # --- Stage 2: Conditional Deepening ---
            deep_decisions = orchestrator._route_deep(probe_results, chat_req.message)

            fired = [p.value for p, d in deep_decisions.items() if d["fire"]]
            skipped = [p.value for p, d in deep_decisions.items() if not d["fire"]]

            yield _sse("stage:deep_start", {
                "firing": fired,
                "skipping": skipped,
                "decisions": {p.value: d for p, d in deep_decisions.items()},
            })

            deep_start = time.monotonic()
            deep_results = await orchestrator._stage2_conditional_deep(
                deep_decisions, probe_results, chat_req.message, chat_req.repo_id,
            )
            deep_ms = (time.monotonic() - deep_start) * 1000

            # Drain wave progress events from W2
            async for wave_event in _drain_wave_queue():
                yield wave_event

            for pipeline, dr in deep_results.items():
                yield _sse(f"deep:{pipeline.value}", {
                    "found_data": dr.found_data,
                    "latency_ms": round(dr.latency_ms, 1),
                    "error": dr.error,
                })

            yield _sse("stage:deep_complete", {"latency_ms": round(deep_ms, 1)})

            # --- Build full orchestrator result for attribution ---
            orch_result = OrchestratorResult()
            orch_result.probe_latency_ms = probe_ms
            orch_result.deep_latency_ms = deep_ms
            # Bug B2 fix: _merge_context is async — must be awaited
            orch_result.context = await orchestrator._merge_context(probe_results, deep_results)

            # Extract intents
            from app.services.query_orchestrator import PipelineName
            intent_probe = probe_results.get(PipelineName.INTENT)
            if intent_probe and intent_probe.data:
                orch_result.intents = intent_probe.data if isinstance(intent_probe.data, list) else [intent_probe.data]

            # Bug B3 fix: run ParamClarificationEngine on streaming path
            # (previously only ran in orchestrator.execute() — non-streaming path)
            try:
                _kb_root = getattr(orchestrator, "_kb_root_for_clarifier", None)
                if _kb_root:
                    _clarifier = getattr(orchestrator, "_param_clarifier", None)
                    if _clarifier is None:
                        from app.brain.param_clarifier import ParamClarificationEngine
                        _clarifier = ParamClarificationEngine(_kb_root)
                        orchestrator._param_clarifier = _clarifier
                    _kc = (
                        orch_result.context.get("knowledge_chunks", [])
                        if isinstance(orch_result.context, dict) else []
                    )
                    _clarification = await _clarifier.check(
                        knowledge_chunks=_kc,
                        query=chat_req.message,
                        company_id=chat_req.company_id or None,
                        session_context=chat_req.metadata or {},
                    )
                    if _clarification:
                        yield _sse("clarification", {
                            "question": _clarification.question,
                            "pending_param": _clarification.pending_param,
                            "api_entity_id": _clarification.api_entity_id,
                        })
                        yield _sse("done", {
                            "session_id": session_id,
                            "needs_clarification": True,
                            "confidence": 0.0,
                            "intents": orch_result.intents,
                        })
                        return
            except Exception as _ce:
                logger.debug("stream.param_clarifier_error", error=str(_ce))

            # --- Write action approval gate (M3-P1 #22) ---
            # Detect cancel-order (and future write action) intents BEFORE LLM streaming.
            # If detected → propose approval, yield approval_required SSE event, return.
            # Operator then re-sends with confirm_action=True + confirm_token to execute.
            try:
                _gate = _get_approval_gate(request)
                if _gate is not None and not chat_req.confirm_action:
                    from app.brain.action_approval import ActionApprovalGate
                    _kc_for_gate = (
                        orch_result.context.get("knowledge_chunks", [])
                        if isinstance(orch_result.context, dict) else []
                    )
                    _write_signal = ActionApprovalGate.detect_write_action(
                        chat_req.message, orch_result.intents, _kc_for_gate
                    )
                    if _write_signal is not None:
                        _proposal = await _gate.propose(
                            session_id=str(session_id),
                            action_type=_write_signal.tool_name,
                            action_input=_write_signal.action_input,
                            summary=_write_signal.summary,
                            risk_level=_write_signal.risk_level,
                        )
                        logger.info(
                            "stream.approval_required",
                            action=_write_signal.tool_name,
                            entity_id=_write_signal.entity_id,
                            token_prefix=_proposal.confirm_token[:8],
                        )
                        yield _sse("approval_required", {
                            "confirm_token": _proposal.confirm_token,
                            "expires_in_seconds": _proposal.ttl_seconds(),
                            "action": _proposal.action_type,
                            "action_input": _proposal.action_input,
                            "summary": _proposal.summary,
                            "risk_level": _proposal.risk_level,
                            "message": (
                                f"This action requires your confirmation: {_proposal.summary}. "
                                f"Re-send with confirm_action=true and the confirm_token provided in this event."
                            ),
                        })
                        yield _sse("done", {
                            "session_id": session_id,
                            "needs_clarification": False,
                            "pending_approval": True,
                            "confidence": 0.9,
                            "intents": orch_result.intents,
                        })
                        return
            except Exception as _ae:
                logger.debug("stream.action_approval_error", error=str(_ae))

            # --- Analytics probe (M3-P2 #24) ---
            # If the analytics probe fired with a company_id, execute the live count
            # and yield an `analytics` SSE event before the LLM response.
            try:
                from app.services.query_orchestrator import PipelineName as _PN
                _analytics_probe = orch_result.pipeline_contributions.get(_PN.ANALYTICS) if hasattr(orch_result, "pipeline_contributions") else None
                # Check probe_results directly on orch_result if available
                _analytics_data = None
                if hasattr(orch_result, "probe_results"):
                    _ap = orch_result.probe_results.get(_PN.ANALYTICS)
                    if _ap and _ap.found_data and _ap.data:
                        _analytics_data = _ap.data
                if _analytics_data and chat_req.icrm_token:
                    from app.config import settings as _settings
                    from app.services.tool_executor import ToolExecutorService, SessionContext as _SC
                    _tool_name = _analytics_data.get("tool_name", "analytics_order_count")
                    _tool_params = {"client_id": int(_analytics_data["company_id"])}
                    if _analytics_data.get("from_date"):
                        _tool_params["from"] = _analytics_data["from_date"]
                    if _analytics_data.get("to_date"):
                        _tool_params["to"] = _analytics_data["to_date"]
                    _executor = ToolExecutorService(settings=_settings, db=None)
                    _actx = _SC(
                        seller_token=chat_req.seller_token,
                        icrm_token=chat_req.icrm_token,
                        approved=True,
                    )
                    try:
                        _result = await _executor.execute(_tool_name, _tool_params, _actx)
                        await _executor.aclose()
                        if _result.status == "success":
                            _count = (
                                _result.data.get("total")
                                or _result.data.get("count")
                                or len(_result.data) if isinstance(_result.data, list) else None
                            )
                            yield _sse("analytics", {
                                "metric": _tool_name,
                                "company_id": _analytics_data["company_id"],
                                "value": _count,
                                "label": _analytics_data.get("date_label"),
                                "from_date": _analytics_data.get("from_date"),
                                "to_date": _analytics_data.get("to_date"),
                                "raw": _result.data,
                            })
                    except Exception as _ae:
                        logger.debug("analytics_probe.execute_error", error=str(_ae))
                        # Graceful degradation — fall through to LLM text answer
            except Exception as _ae:
                logger.debug("analytics_probe.error", error=str(_ae))

            # --- Stage 3: LLM Assembly ---
            yield _sse("stage:llm_start", {})

            llm_context = _build_llm_context(orch_result)
            engine = _get_react_engine(request)

            if engine is not None:
                augmented_context = {
                    "user_id": chat_req.user_id,
                    "company_id": chat_req.company_id,
                    "channel": chat_req.channel,
                    "pipeline_context": llm_context,
                }
                augmented_context.update(chat_req.metadata)

                # Bug B1 fix: classification was undefined in this scope.
                # Use request_classification if populated, else empty dict.
                # complexity defaults to "standard" which is correct for most queries.
                classification = orch_result.request_classification or {}

                # True token-level streaming via RIPER.stream_final_response()
                t0 = time.monotonic()
                riper = getattr(orchestrator, "riper_engine", None)

                if riper is not None and hasattr(riper, "stream_final_response"):
                    # True streaming: yields {"event":"phase"|"chunk"|"done", ...}
                    async for item in riper.stream_final_response(
                        query=chat_req.message,
                        context=orch_result.context,
                        intents=orch_result.intents,
                        complexity=classification.get("complexity", "standard"),
                    ):
                        ev = item.get("event", "chunk")
                        if ev == "chunk":
                            yield _sse("chunk", {"text": item.get("text", "")})
                        elif ev == "phase":
                            yield _sse(f"riper_phase:{item.get('phase', '')}", item)
                        elif ev == "done":
                            confidence = item.get("confidence", 0.5)
                            tools_used = item.get("tools_used", [])
                else:
                    # Fallback: non-streaming ReAct process + chunked emit
                    result = await engine.process(chat_req.message, augmented_context)
                    response_text = result.response
                    for i in range(0, len(response_text), 40):
                        yield _sse("chunk", {"text": response_text[i:i + 40]})
                    confidence = result.confidence
                    tools_used = result.tools_used

                llm_ms = (time.monotonic() - t0) * 1000
            else:
                content = f"Based on pipeline analysis:\n\n{llm_context}"
                for i in range(0, len(content), 40):
                    yield _sse("chunk", {"text": content[i:i + 40]})
                confidence = 0.5
                tools_used = []
                llm_ms = 0.0

            # Attribution
            # Build attribution manually for streaming
            attribution = {
                "pipeline_breakdown": {},
                "timing": {
                    "probe_ms": round(probe_ms, 1),
                    "deep_ms": round(deep_ms, 1),
                    "llm_ms": round(llm_ms, 1),
                    "total_ms": round(probe_ms + deep_ms + llm_ms, 1),
                },
            }
            for p, pr in probe_results.items():
                attribution["pipeline_breakdown"][p.value] = {
                    "stage": "probe",
                    "contributed": pr.found_data,
                    "latency_ms": round(pr.latency_ms, 1),
                }
            for p, dr in deep_results.items():
                attribution["pipeline_breakdown"][p.value] = {
                    "stage": "deep",
                    "contributed": dr.found_data,
                    "latency_ms": round(dr.latency_ms, 1),
                }
            for p, d in deep_decisions.items():
                if not d["fire"] and p.value not in attribution["pipeline_breakdown"]:
                    attribution["pipeline_breakdown"][p.value] = {
                        "stage": "deep",
                        "contributed": False,
                        "skipped": True,
                        "reason": d["reason"],
                    }

            yield _sse("attribution", attribution)

            yield _sse("done", {
                "session_id": session_id,
                "confidence": confidence,
                "tools_used": tools_used,
                "intents": orch_result.intents,
            })

        except Exception as exc:
            logger.error("hybrid_chat_stream.error", error_code="ERR-COSMOS-500", error=type(exc).__name__)
            yield _sse("error", {"message": "An internal error occurred. Please try again."})

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@router.get("/analytics")
async def pipeline_analytics(request: Request):
    """
    Returns aggregated pipeline attribution analytics.
    Use this to identify which pipelines are core vs. burden.
    """
    # For now, return the current orchestrator configuration.
    # In production, this would query a query_analytics table.
    orchestrator = _get_orchestrator(request)
    if orchestrator is None:
        return {"status": "orchestrator not initialized"}

    return {
        "status": "active",
        "architecture": "hybrid_two_stage",
        "stage_1_probes": [
            "intent_classifier",
            "entity_lookup",
            "vector_search",
            "page_role",
            "cross_repo",
        ],
        "stage_2_deep_candidates": [
            "graph_rag_deep",
            "cross_repo_deep",
            "session_history",
        ],
        "routing_rules": {
            "graph_rag_deep": "fires when trace/why intent + vector nodes found (top_relevance > 0.4)",
            "cross_repo_deep": "fires when cross-repo mapping found + sync/system keywords",
            "session_history": "fires when no entity_id extracted from query",
        },
        "tip": "Add ?debug=true to /hybrid/chat to see per-query attribution breakdown",
    }


# ---------------------------------------------------------------------------
# SSE Helper
# ---------------------------------------------------------------------------

def _sse(event: str, data: dict) -> str:
    return f"event: {event}\ndata: {json.dumps(data, default=str)}\n\n"
